- src/main/java/org/apache/maven/plugins/clean/Cleaner.java
> [MCLEAN-104] Prevent NPE in fast mode and quiet build

- pom.xml
- src/main/java/org/apache/maven/plugins/clean/Cleaner.java
- src/main/java/org/apache/maven/plugins/clean/GlobSelector.java
JIRA issue: https://issues.apache.org/jira/projects/MCLEAN/issues/MCLEAN-107
> [MCLEAN-107] Upgrade to plexus-utils 4.0.0 and plexus-xml 4.0.0

- pom.xml
> [MCLEAN-112] Bump parent to 40

- pom.xml
It is only needed for testing so move to test scope
---
To make clear …
> [MCLEAN-113] Downgrade plexus-xml to 3.0.0

- src/site/xdoc/download.xml.vm
> [MCLEAN-114] Refresh download page

- pom.xml
- src/site/apt/examples/delete_additional_files.apt.vm
https://issues.apache.org/jira/browse/MCLEAN-118
> [MCLEAN-118] Require Maven 3.6.3

- .github/workflows/maven-verify.yml
> Build with Maven 4

- .github/release-drafter-3.x.yml
- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
> Add Release Drafter

- .github/workflows/release-drafter.yml
> Add Release Drafter - 3.x

- .github/release-drafter-3.x.yml
- .github/release-drafter.yml
> Use resolved versions in release drafter

- .github/release-drafter.yml
> Use COMPLETE for version-template in release drafter

- LICENSE
- NOTICE
(cherry picked from commit 30b89ca3ac0c8e96c4fe70ba88d5fe35c8526ed9) …
> Fix license/notice

- .github/release-drafter-3.x.yml
> Add configuration for pre-release in master

- .github/workflows/release-drafter.yml
> release-drafter configuration

- README.md
> Add badge for 3.x version

- .github/workflows/maven-verify.yml
> Simplify GH action

- .github/release-drafter.yml
> Add header to release-drafter about Maven 4 requirements

- pom.xml
As property maven.site.path is used in many other place we have to override it
> Override maven.site.path property for 4.x publishing

- pom.xml
> Update scm tag according to branch

- pom.xml
- src/main/java/org/apache/maven/plugins/clean/CleanMojo.java
- src/main/java/org/apache/maven/plugins/clean/Cleaner.java
- src/main/java/org/apache/maven/plugins/clean/Fileset.java
- src/main/java/org/apache/maven/plugins/clean/GlobSelector.java
* Remove an unused dependency
* Add missing `@Override` annotations
* Avoid an usage of `/` path separator.
> Minor cleaning: dependency, `@Override`, `Paths`

- .github/pull_request_template.md
- .github/release-drafter-3.x.yml
- .github/release-drafter.yml
- README.md
> Update release-drafter, README and PR template after parent 44

- src/site/site.xml
> Update site descriptor

- .github/workflows/maven-verify.yml
- pom.xml
Replace #263 (needs more changes in the `pom.xml`).
> Upgrade Maven core dependency to 4.0.0-rc-4.
